### ISSUE TITLE
RuntimeException: error: could not create FastTypeTag for class 'scala.None$'

### ISSUE THREAD

**Issue by kosii** [scala/pickling#253]
When executing the following code: 
```scala
def appendLog[T: SPickler : FastTypeTag](entry: Either[Option[Int], T]) = entry.pickle
appendLog[Int](Right(6))
appendLog[Int](Left(None))
```
I get a runtime exception for the second call like this:
```
Exception in thread "main" java.lang.RuntimeException: error: could not create FastTypeTag for class 'scala.None$'
	at scala.sys.package$.error(package.scala:27)
	at scala.pickling.FastTypeTag$.mkRaw(FastTags.scala:176)
	at test.PPP$ScalaUtilLeft$u005BscalaAny$u002CscalaAny$u005DPickler$macro$1$2$$anonfun$pickle$1.apply(PPP.scala:14)
	at test.PPP$ScalaUtilLeft$u005BscalaAny$u002CscalaAny$u005DPickler$macro$1$2$$anonfun$pickle$1.apply(PPP.scala:14)
	at scala.pickling.json.JSONPickleBuilder.putField(JSONPickleFormat.scala:137)
	at test.PPP$ScalaUtilLeft$u005BscalaAny$u002CscalaAny$u005DPickler$macro$1$2$.pickle(PPP.scala:14)
	at test.PPP$ScalaUtilLeft$u005BscalaAny$u002CscalaAny$u005DPickler$macro$1$2$.pickle(PPP.scala:14)
	at test.PPP$.appendLog(PPP.scala:14)
	at test.PPP$.delayedEndpoint$test$PPP$1(PPP.scala:16)
	at test.PPP$delayedInit$body.apply(PPP.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at test.PPP$.main(PPP.scala:13)
	at test.PPP.main(PPP.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

I tried to minimize my code, but any of these made the exception disappear:
* replace T with a concrete type in the function parameters: `def appendLog[T: SPickler : FastTypeTag](entry: Either[Option[Int], Int]) = entry.pickle`
* remove the Option: `def appendLog[T: SPickler : FastTypeTag](entry: Either[Int, T]) = entry.pickle`
* remove the Either: `def appendLog[T: SPickler : FastTypeTag](entry: Option[T]) = entry.pickle`

**Comment by eed3si9n** [comment]
I cannot reproduce the error using Pickling 0.10.0.

``` scala
scala> import scala.pickling._, Defaults._, json._
import scala.pickling._
import Defaults._
import json._

scala> def appendLog[T: Pickler : FastTypeTag](entry: Either[Option[Int], T]) = entry.pickle
appendLog: [T](entry: Either[Option[Int],T])(implicit evidence$1: scala.pickling.Pickler[T], implicit evidence$2: scala.pickling.FastTypeTag[T])scala.pickling.json.pickleFormat.PickleType

scala> appendLog[Int](Right(6))
res0: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "scala.util.Right[scala.Any,scala.Any]",
  "b": {
    "$type": "scala.Int",
    "value": 6
  }
})

scala> appendLog[Int](Left(None))
res1: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "scala.util.Left[scala.Any,scala.Any]",
  "a": {
    "$type": "scala.None$"
  }
})
```

Not sure how you can unpickle this correctly.

**Comment by kosii** [comment]
Thank you for testing, I was using 0.9.0, but it seems to work with 0.10.0. I also forgot to import static._, that's why I got a run-time error instead of a compilation error.
