### ISSUE TITLE
unpickle not a member of Array[Byte]

### ISSUE THREAD

**Issue by davidmweber** [scala/pickling#221]
In 0.8.0 and 0.9.0-SNAPSHOT, you could unpickle an Array[Byte], but it appears to be broken or the API has changed in 0.9.0. Here is an example that no longer works in 0.9.0:

``` scala
  import scala.pickling._
  import binary._

  val bar: String = "abcd"
  val foo: Array[Byte] = bar.pickle.value
  val pop = foo.unpickle[String]
```

This generates a message "value unpickle is not a member of Array[Byte]"

Thanks
